-- Auto Backup for MySQL Professional Edition 3.0
--
-- Host: localhost
--
-- MySQL Server Version: 5.5.11
--
-- 2012-01-12 19:19:57
--
-- ------------------------------------------------------

SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT;
SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS;
SET @OLD_CHARACTER_SET_CONNECTION=@@CHARACTER_SET_CONNECTION;
SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS;
SET UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE;
SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET @OLD_SQL_NOTES=@@SQL_NOTES;
SET SQL_NOTES=0;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `book_details`;
CREATE TABLE IF NOT EXISTS `book_details` (  `acc_no` int(10) NOT NULL,  `title` varchar(50) DEFAULT NULL,  `authors` varchar(50) DEFAULT NULL,  `publisher_ID` int(15) DEFAULT NULL,  `pub_name` varchar(30) DEFAULT NULL,  `price` float(10,2) DEFAULT NULL,  `pages` int(10) DEFAULT NULL,  `edition` int(4) DEFAULT NULL,  `pur_date` date DEFAULT NULL,  `status` char(1) DEFAULT 'Y',  `category` varchar(30) DEFAULT NULL,  PRIMARY KEY (`acc_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `book_details` DISABLE KEYS;
LOCK TABLES `book_details` WRITE;
INSERT INTO `book_details` VALUES (1002,'God of Small Things','Arundhati Roy',767584,'Dhanpat Raai',530.00,680,2005,'2006-04-09','Y','Drama');
INSERT INTO `book_details` VALUES (1003,'Terminal','Robin Cook',767584,'Dhanpat Raai',600.00,678,2010,'2011-02-23','N','Horror');
INSERT INTO `book_details` VALUES (1005,'The Dark Night','Bianca',768456,'Sangeeta Roy',460.00,456,2011,'2010-09-21','Y','Horror');
INSERT INTO `book_details` VALUES (1006,'The Reptiles and Mammals','Priyanka Sharma',767584,'Dhanpat Raai',230.00,246,2008,'2009-02-21','Y','Encyclopedia');
INSERT INTO `book_details` VALUES (1007,'Physics Reference-XII','S.K.Pradeep',767584,'Dhanpat Raai',430.00,376,2008,'2009-02-09','Y','Physics');
INSERT INTO `book_details` VALUES (1008,'Chemistry ABC Reference-X','S.Chand',767584,'Dhanpat Raai',230.00,678,2009,'2010-11-29','N','Chemistry');
INSERT INTO `book_details` VALUES (1009,'Oxford Reference-VI','John Fernandes',673893,'Jessica Lalwani',100.00,453,2001,'2003-07-11','Y','Literature');
INSERT INTO `book_details` VALUES (1011,'Romeo Juliet','Robert Frost',689634,'Agatha Cristie',650.00,320,2010,'2010-04-19','Y','Drama');
INSERT INTO `book_details` VALUES (1012,'FULL MARKS-X','Sumeeta Arora',767584,'Dhanpat Raai',250.00,345,2011,'2011-02-18','Y','Mathematics');
INSERT INTO `book_details` VALUES (1013,'Munshi Prem Chandra','Sandhya Das',768950,'Suneett Arora ',300.00,445,2010,'2011-12-10','Y','Hindi');
INSERT INTO `book_details` VALUES (1015,'Seven Things','Agatha Cristie',768917,'Jackie Mathew',290.00,342,2010,'2011-02-03','N','Fiction');
INSERT INTO `book_details` VALUES (1016,'A Thing of Beauty','Robert Frost',798980,'Jack Mathew',230.00,290,2011,'2011-09-14','N','Fiction');
UNLOCK TABLES;
ALTER TABLE `book_details` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class1`;
CREATE TABLE IF NOT EXISTS `class1` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `class` varchar(4) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class1` DISABLE KEYS;
LOCK TABLES `class1` WRITE;
INSERT INTO `class1` VALUES (1245,101,'priya karode','N','1','A Thing of Beauty');
INSERT INTO `class1` VALUES (1337,105,'simran chandwani','Y','1',' NULL');
INSERT INTO `class1` VALUES (1385,102,'Nivetha selveraj','N','1','Seven Things');
INSERT INTO `class1` VALUES (1857,103,'maurvi shukla','Y','1',' NULL');
UNLOCK TABLES;
ALTER TABLE `class1` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class10`;
CREATE TABLE IF NOT EXISTS `class10` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `class` varchar(3) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class10` DISABLE KEYS;
LOCK TABLES `class10` WRITE;
INSERT INTO `class10` VALUES (9076,1001,'Suraj singh','X','Y',' NULL');
UNLOCK TABLES;
ALTER TABLE `class10` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class11`;
CREATE TABLE IF NOT EXISTS `class11` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `class` varchar(3) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class11` DISABLE KEYS;
LOCK TABLES `class11` WRITE;
INSERT INTO `class11` VALUES (6586,1101,'Mahek Patel','XI','Y',' NULL');
UNLOCK TABLES;
ALTER TABLE `class11` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class12`;
CREATE TABLE IF NOT EXISTS `class12` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `class` varchar(3) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class12` DISABLE KEYS;
LOCK TABLES `class12` WRITE;
INSERT INTO `class12` VALUES (3479,1203,'Akansha Agarwal','XII','Y',' NULL');
INSERT INTO `class12` VALUES (3679,1204,'Adrishi Yadav','XII','Y',' NULL');
INSERT INTO `class12` VALUES (6759,1202,'Devendra Pandey','XII','Y',' NULL');
INSERT INTO `class12` VALUES (6789,1201,'Praveen Dave','XII','Y',' NULL');
UNLOCK TABLES;
ALTER TABLE `class12` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class2`;
CREATE TABLE IF NOT EXISTS `class2` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `class` varchar(3) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class2` DISABLE KEYS;
LOCK TABLES `class2` WRITE;
INSERT INTO `class2` VALUES (3547,201,'shivangi jain','II','Y',' NULL');
INSERT INTO `class2` VALUES (3763,203,'kim singh','II','Y',' NULL');
INSERT INTO `class2` VALUES (7843,204,'janvi singh','II','Y',' NULL');
UNLOCK TABLES;
ALTER TABLE `class2` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class3`;
CREATE TABLE IF NOT EXISTS `class3` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `class` varchar(3) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class3` DISABLE KEYS;
LOCK TABLES `class3` WRITE;
INSERT INTO `class3` VALUES (6683,302,'Sunita vaswani','III','Y',' NULL');
INSERT INTO `class3` VALUES (7253,301,'Akshay sharma','III','Y',' NULL');
UNLOCK TABLES;
ALTER TABLE `class3` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class4`;
CREATE TABLE IF NOT EXISTS `class4` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `class` varchar(3) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class4` DISABLE KEYS;
LOCK TABLES `class4` WRITE;
INSERT INTO `class4` VALUES (1456,402,'Sarita Sharma','Y','4','NULL');
INSERT INTO `class4` VALUES (6743,401,'Shalley vaswani','IV','Y',' NULL');
UNLOCK TABLES;
ALTER TABLE `class4` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class5`;
CREATE TABLE IF NOT EXISTS `class5` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `class` varchar(3) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class5` DISABLE KEYS;
LOCK TABLES `class5` WRITE;
INSERT INTO `class5` VALUES (6753,501,'Shweta goyal','V','Y',' NULL');
UNLOCK TABLES;
ALTER TABLE `class5` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class6`;
CREATE TABLE IF NOT EXISTS `class6` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `class` varchar(3) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class6` DISABLE KEYS;
LOCK TABLES `class6` WRITE;
INSERT INTO `class6` VALUES (1353,601,'Neha basin','VI','Y',' NULL');
UNLOCK TABLES;
ALTER TABLE `class6` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class7`;
CREATE TABLE IF NOT EXISTS `class7` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `class` varchar(3) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class7` DISABLE KEYS;
LOCK TABLES `class7` WRITE;
INSERT INTO `class7` VALUES (7853,701,'Avni palekar','VII','Y',' NULL');
UNLOCK TABLES;
ALTER TABLE `class7` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class8`;
CREATE TABLE IF NOT EXISTS `class8` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `class` varchar(5) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class8` DISABLE KEYS;
LOCK TABLES `class8` WRITE;
INSERT INTO `class8` VALUES (4553,801,'Bhaskar mishra','VIII','Y',' NULL');
UNLOCK TABLES;
ALTER TABLE `class8` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `class9`;
CREATE TABLE IF NOT EXISTS `class9` (  `addmission_no` int(10) NOT NULL,  `Roll_no` int(10) DEFAULT NULL,  `Stu_name` varchar(30) DEFAULT NULL,  `class` varchar(3) DEFAULT NULL,  `Status` char(1) DEFAULT NULL,  `book_issued` varchar(50) DEFAULT NULL,  PRIMARY KEY (`addmission_no`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `class9` DISABLE KEYS;
LOCK TABLES `class9` WRITE;
INSERT INTO `class9` VALUES (4763,901,'Amit bhandari','IX','Y',' NULL');
UNLOCK TABLES;
ALTER TABLE `class9` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `publisher`;
CREATE TABLE IF NOT EXISTS `publisher` (  `pub_id` int(4) NOT NULL,  `pub_name` varchar(30) NOT NULL,  `pub_address` varchar(60) DEFAULT NULL,  `pub_phone` varchar(15) DEFAULT NULL,  `pub_phone2` varchar(15) DEFAULT NULL,  `status` char(1) DEFAULT NULL,  PRIMARY KEY (`pub_id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `publisher` DISABLE KEYS;
LOCK TABLES `publisher` WRITE;
INSERT INTO `publisher` VALUES (767584,'Dhanpat Raai','GandhiMarg,New Delhi','011-234569','7682234220','Y');
INSERT INTO `publisher` VALUES (768456,'Sangeeta Roy',' K Sons Publications,Gurgoenn','011245657','9980987869','Y');
INSERT INTO `publisher` VALUES (768950,'Suneett Arora ','Chawla Chouk,New Delhi','965840878','766483022','Y');
INSERT INTO `publisher` VALUES (789567,'Rachna Sagar','Shanti Grah Publications,Mumbai','932427829','745244278','Y');
UNLOCK TABLES;
ALTER TABLE `publisher` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `sissue`;
CREATE TABLE IF NOT EXISTS `sissue` (  `ADDMISSION_NO` int(15) NOT NULL,  `ROLL_NO` int(10) DEFAULT NULL,  `stu_name` varchar(30) DEFAULT NULL,  `CLASS` varchar(4) DEFAULT NULL,  `ISSUE_DATE` date DEFAULT NULL,  `RETURN_DATE` date DEFAULT NULL,  `book_issued` varchar(60) DEFAULT NULL,  PRIMARY KEY (`ADDMISSION_NO`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `sissue` DISABLE KEYS;
LOCK TABLES `sissue` WRITE;
INSERT INTO `sissue` VALUES (1245,101,'priya karode','1','2011-11-05','2011-11-15','A Thing of Beauty');
INSERT INTO `sissue` VALUES (1385,102,'Nivetha selveraj','1','2011-11-05','2011-11-15','Seven Things');
UNLOCK TABLES;
ALTER TABLE `sissue` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `sissuet`;
CREATE TABLE IF NOT EXISTS `sissuet` (  `Tno` int(15) NOT NULL,  `Tname` varchar(30) DEFAULT NULL,  `Taddress` varchar(50) DEFAULT NULL,  `Issue_date` date DEFAULT NULL,  `return_date` date DEFAULT NULL,  `book_issued` varchar(60) DEFAULT NULL,  PRIMARY KEY (`Tno`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `sissuet` DISABLE KEYS;
LOCK TABLES `sissuet` WRITE;
INSERT INTO `sissuet` VALUES (500311,'Shabnam Sharma','Sector B,Gandhidham','2011-11-05','2011-11-15','Terminal');
INSERT INTO `sissuet` VALUES (500312,'Ekta Singh','IFFCO colony,Gandhidham','2011-11-05','2011-11-15','Chemistry ABC Reference-X');
UNLOCK TABLES;
ALTER TABLE `sissuet` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `teacher`;
CREATE TABLE IF NOT EXISTS `teacher` (  `tcode` int(10) DEFAULT NULL,  `tname` varchar(20) DEFAULT NULL,  `address` varchar(70) DEFAULT NULL,  `SALARY` float(10,2) DEFAULT NULL,  `dept` int(5) DEFAULT NULL,  `join_date` date DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `teacher` DISABLE KEYS;
LOCK TABLES `teacher` WRITE;
INSERT INTO `teacher` VALUES (NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `teacher` VALUES (1002,'NIRALI','GREEN LEMON APPT,GANDHIDHAM',17000.00,4499,'2010-11-17');
INSERT INTO `teacher` VALUES (1003,'KRUSHANT','EKC COLONY,ADIPUR',21000.00,4435,'2011-06-30');
INSERT INTO `teacher` VALUES (1004,'GOLDEN','SHIVAJI PARK,GANDHIDHAM',19000.00,4489,'2011-05-11');
INSERT INTO `teacher` VALUES (1001,'TRIPTI','VAIKUNTH SOC. ,ADIPUR',23000.00,4578,'2005-05-30');
UNLOCK TABLES;
ALTER TABLE `teacher` ENABLE KEYS;
SET CHARACTER_SET_CLIENT='latin1';
SET CHARACTER_SET_RESULTS='latin1';
SET CHARACTER_SET_CONNECTION='latin1';
SET NAMES 'latin1';
CREATE DATABASE IF NOT EXISTS `school` DEFAULT CHARACTER SET latin1;
USE `school`;

DROP TABLE IF EXISTS `teacherdtl`;
CREATE TABLE IF NOT EXISTS `teacherdtl` (  `Tno` int(10) DEFAULT NULL,  `Tname` varchar(30) DEFAULT NULL,  `Taddress` varchar(50) DEFAULT NULL,  `Tphone` varchar(15) DEFAULT NULL,  `current_issuedbook` varchar(50) DEFAULT NULL,  `Status` char(1) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `teacherdtl` DISABLE KEYS;
LOCK TABLES `teacherdtl` WRITE;
INSERT INTO `teacherdtl` VALUES (500311,'Shabnam Sharma','Sector B,Gandhidham','9989824345','Terminal','N');
INSERT INTO `teacherdtl` VALUES (500312,'Ekta Singh','IFFCO colony,Gandhidham','9428735345','Chemistry ABC Reference-X','N');
INSERT INTO `teacherdtl` VALUES (500314,'Neena Francis','Gandhi Samadhi,Adipur','9675445367','NULL','Y');
INSERT INTO `teacherdtl` VALUES (500315,'Vishal Tonk','Adisar Pond,Adipur','8190825372','NULL','Y');
INSERT INTO `teacherdtl` VALUES (500316,'Preeti Sharma','Sector C9,Gandhidham','8173373972','NULL','Y');
INSERT INTO `teacherdtl` VALUES (500317,'Chetan Chauhan','Gandhi Market,Gandhidham','8546748353','NULL','Y');
UNLOCK TABLES;
ALTER TABLE `teacherdtl` ENABLE KEYS;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET SQL_NOTES=@OLD_SQL_NOTES;
SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT;
SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS;
SET CHARACTER_SET_CONNECTION=@OLD_CHARACTER_SET_CONNECTION;
SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION;
